name: Hourly Data Update

on:
  schedule:
    - cron: "0 * * * *" # Каждый час в :00 минут
  workflow_dispatch: # Для ручного запуска

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET "https://no-spicy-loyverse.vercel.app/api/update-sales")
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Status code: $status_code"
          echo "Response body: $body"

          if [ "$status_code" -ne 200 ]; then
            echo "Error: Request failed with status $status_code"
            echo "$body"
            exit 1
          fi
